<a href="https://colab.research.google.com/github/channel1umut-lang/Python-for-Data-Science/blob/main/0001_Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#!pip install numpy --- if import does not work

In [ ]:
my_list = [10,20,30,40]

In [ ]:
type(my_list)

list

In [ ]:
np.array(my_list)

array([10, 20, 30, 40])

In [ ]:
my_nump_array = np.array(my_list)

In [ ]:
type(my_nump_array)

numpy.ndarray

In [ ]:
my_nump_array.max() #you can do more operation via numpy library more than the python itself

np.int64(40)

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.random.randint(1,150,5) #between 1 to 150, and creats 5 numbers

array([ 57,  60, 137, 105,  86])

In [ ]:
np.random.random(5)

array([0.72254644, 0.46814198, 0.67565629, 0.9809736 , 0.82737151])

In [ ]:
#array arithmatic

In [ ]:
my_list1 = [4,2]

In [ ]:
my_list2 = [2,3]

In [ ]:
my_list1 + my_list2

[4, 2, 2, 3]

In [ ]:
my_nump_array1 = np.array(my_list1)

In [ ]:
my_nump_array2 = np.array(my_list2)

In [ ]:
my_nump_array1 + my_nump_array2 # the sum of indexs`

array([6, 5])

In [ ]:
my_nump_array1 * my_nump_array2

array([8, 6])

In [ ]:
my_nump_array1 / my_nump_array2

array([2.        , 0.66666667])

In [ ]:
my_nump_array1 - my_nump_array2

array([ 2, -1])

In [ ]:
my_nump_array1 % my_nump_array2

array([0, 2])

In [ ]:
my_nump_array1 ** my_nump_array2

array([16,  8])

In [ ]:
my_nump_array1 // my_nump_array2 #the floor division // rounds the result down to the nearest whole number (rounding operation) - sonucu en yakin tam sayiya yuvarlama islemi

array([2, 0])

In [ ]:
my_nump_array1 > my_nump_array2

array([ True, False])

In [ ]:
my_nump_array1 < my_nump_array2

array([False,  True])

In [ ]:
my_list1 * 5

[4, 2, 4, 2, 4, 2, 4, 2, 4, 2]

In [ ]:
othert_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
othert_array.min()

np.int64(1)

In [ ]:
othert_array.sum()

np.int64(55)

In [ ]:
othert_array.mean() #avg.

np.float64(5.5)

In [ ]:
othert_array.std() #standart devietion

np.float64(2.8722813232690143)

In [ ]:
my_nump_array1

array([4, 2])

In [ ]:
othert_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#othert_array + my_nump_array1 it does not sum because different idexs

In [ ]:
#arange and indexing

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np_array =  np.arange(0,10)

In [ ]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np_array[1] # logic of index valid here too

np.int64(1)

In [ ]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
np_array[-3:0:-2]# starts in -3nd index reduces 2 for each steps until 0

array([7, 5, 3, 1])

In [ ]:
#random

In [ ]:
np.random.randn(4,4) # it gave matrix 4*4

array([[ 0.32169537,  0.08162498, -1.48588965,  0.40598054],
       [-1.76637809,  0.08310839,  1.8371203 , -0.16347681],
       [-0.0822398 , -1.26733212,  0.16345808,  0.43258267],
       [-0.76002679,  0.98729019,  0.22823669,  0.96206111]])

In [ ]:
np.random.randint(1,300,10)

array([149, 293, 255, 279,  39,  80, 286, 209, 107, 185])