<a href="https://colab.research.google.com/github/channel1umut-lang/Python-for-Data-Science/blob/main/0002_Numpy_Matrixes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_matrix = [[5,10],[15,20]]

In [ ]:
my_matrix[0]

[5, 10]

In [ ]:
my_matrix[1]

[15, 20]

In [ ]:
my_matrix[0][1]

10

In [ ]:
#row*column

In [ ]:
numpy_matrix = np.array([[5,10],[15,20]])

In [ ]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [ ]:
numpy_matrix[1][0]

np.int64(15)

In [ ]:
numpy_matrix.sum()

np.int64(50)

In [ ]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#matrix arithmetic

In [ ]:
first_array = np.array ([[10,20],[30,40]])

In [ ]:
second_array = np.array([[5,15],[25,35]])

In [ ]:
first_array , second_array

(array([[10, 20],
        [30, 40]]),
 array([[ 5, 15],
        [25, 35]]))

In [ ]:
first_array*second_array

array([[  50,  300],
       [ 750, 1400]])

In [ ]:
first_array

array([[10, 20],
       [30, 40]])

In [ ]:
third_array = np.array([[50,60]])

In [ ]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [ ]:
fourth_array = np.array([[10,20,30,40,50]])

In [ ]:
fourth_array

array([[10, 20, 30, 40, 50]])

In [ ]:
#fourth_array + first_array does not sum because they do not dimentionally equal

In [ ]:
third_array = np.array ([[10],[20]])

In [ ]:
third_array

array([[10],
       [20]])

In [ ]:
third_array.shape #2= satir, 1 = column

(2, 1)

In [ ]:
first_array

array([[10, 20],
       [30, 40]])

In [ ]:
first_array + third_array #usttekilere 10 eklemis , alttakilere 20 eklemis

array([[20, 30],
       [50, 60]])

In [ ]:
#matrix multiplication

In [ ]:
first_array

array([[10, 20],
       [30, 40]])

In [ ]:
second_array

array([[ 5, 15],
       [25, 35]])

In [ ]:
first_array*second_array

array([[  50,  300],
       [ 750, 1400]])

In [ ]:
#dot product

In [ ]:
first_matrix = np.array([[10,20,30]])

In [ ]:
first_matrix

array([[10, 20, 30]])

In [ ]:
first_matrix.shape

(1, 3)

In [ ]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [ ]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [ ]:
second_matrix.shape

(3, 2)

In [ ]:
first_matrix.dot(second_matrix)

array([[120, 180]])