<a href="https://colab.research.google.com/github/channel1umut-lang/Python-for-Data-Science/blob/main/0003_Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
new_array = np.random.randint(1, 100, 20)

In [ ]:
new_array

array([13, 84, 98, 11, 86, 20, 58, 40, 85, 40, 81, 53, 20, 82, 56, 31, 99,
       56, 45,  9])

In [ ]:
new_array>25

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False])

In [ ]:
new_array[new_array>25]

array([84, 98, 86, 58, 40, 85, 40, 81, 53, 82, 56, 31, 99, 56, 45])

In [ ]:
new_array[new_array<25]

array([13, 11, 20, 20,  9])

In [ ]:
#transpose and reshape operations

In [ ]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [ ]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [ ]:
matrix_array.shape

(3, 2)

In [ ]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [ ]:
matrix_array.T #ayni

array([[10, 20, 30],
       [20, 30, 40]])

In [ ]:
random_array = np.random.random((6,1))

In [ ]:
random_array

array([[0.20126474],
       [0.97604206],
       [0.12181002],
       [0.82761897],
       [0.41805694],
       [0.78335015]])

In [ ]:
random_array.reshape(2,3)

array([[0.20126474, 0.97604206, 0.12181002],
       [0.82761897, 0.41805694, 0.78335015]])

In [ ]:
random_array.reshape(3,2)

array([[0.20126474, 0.97604206],
       [0.12181002, 0.82761897],
       [0.41805694, 0.78335015]])

In [ ]:
#z-score

In [ ]:
data = np.array([10,12,13,14,15,16,100,105])

In [ ]:
#outlier

In [ ]:
mean = np.mean(data)

In [ ]:
mean

np.float64(35.625)

In [ ]:
data.sum()/len(data)

np.float64(35.625)

In [ ]:
std = np.std(data)

In [ ]:
std

np.float64(38.668260563412986)

In [ ]:
z_scores = (data - mean) / std

In [ ]:
z_scores

array([-0.6626882 , -0.61096619, -0.58510519, -0.55924419, -0.53338319,
       -0.50752218,  1.66480206,  1.79410708])

In [ ]:
data[z_scores>1]

array([100, 105])

In [ ]:
#math equetions

In [ ]:
# 2x + 3y = 8 and 5x + 7y = 19

In [ ]:
#coeffcients

In [ ]:
A = np.array([[2,3],[5,7]])

In [ ]:
B = np.array([8,19])

In [ ]:
solution = np.linalg.solve(A,B)

In [ ]:
solution #x=1, y=2

array([1., 2.])